/*
 * The one skills/keywords dictionary used for both resumes and job postings
 * (spec 006). Key = canonical name shown in the UI; value = extra spellings.
 * The canonical name itself is always matched, so list only alternatives.
 *
 * Deliberately excluded: words too ambiguous to detect from plain text
 * ("Go", "R", "C", "Swift" as a verb...). Use the unambiguous spelling
 * ("Golang", "R programming") instead.
 */
export const SKILLS: Record<string, string[]> = {
  // Languages
  JavaScript: ["js", "ecmascript", "es6"],
  TypeScript: [],
  Python: ["python3"],
  Java: [],
  Kotlin: [],
  Scala: [],
  "C++": ["cpp"],
  "C#": ["csharp", "c sharp"],
  Golang: ["go lang"],
  Rust: [],
  Ruby: [],
  PHP: [],
  "Swift (iOS)": ["swiftui", "swift ui"],
  "Objective-C": ["objective c"],
  "R programming": ["rstudio", "r studio"],
  MATLAB: [],
  Perl: [],
  Bash: ["shell scripting", "shell script"],
  PowerShell: [],
  Dart: [],
  Elixir: [],
  Haskell: [],
  Solidity: [],
  SQL: ["t-sql", "tsql", "pl/sql", "plsql"],
  HTML: ["html5"],
  CSS: ["css3"],
  Sass: ["scss"],

  // Frontend
  React: ["react.js", "reactjs"],
  "Next.js": ["nextjs"],
  "React Native": [],
  Redux: [],
  Angular: ["angularjs", "angular.js"],
  "Vue.js": ["vue", "vuejs", "nuxt", "nuxt.js"],
  Svelte: ["sveltekit"],
  "Tailwind CSS": ["tailwind", "tailwindcss"],
  Bootstrap: [],
  jQuery: [],
  Webpack: [],
  Vite: [],
  "Web accessibility": ["wcag", "a11y", "accessibility"],
  "Design systems": ["design system"],
  Storybook: [],
  "Three.js": ["threejs", "webgl"],
  D3: ["d3.js", "d3js"],
  Flutter: [],
  "iOS development": ["ios"],
  "Android development": ["android"],

  // Backend / APIs
  "Node.js": ["node", "nodejs"],
  "Express.js": ["expressjs"],
  NestJS: ["nest.js"],
  Django: [],
  Flask: [],
  FastAPI: [],
  "Spring Boot": ["spring framework", "spring mvc"],
  "Ruby on Rails": ["rails", "ror"],
  Laravel: [],
  ".NET": ["dotnet", "asp.net", ".net core"],
  GraphQL: ["apollo"],
  "REST APIs": ["rest api", "restful", "restful apis"],
  gRPC: [],
  Microservices: ["microservice", "micro-services"],
  WebSockets: ["websocket"],
  "Event-driven architecture": ["event driven"],
  "System design": ["distributed systems", "distributed system"],

  // Data stores
  PostgreSQL: ["postgres", "psql"],
  MySQL: [],
  "SQL Server": ["mssql", "microsoft sql server"],
  Oracle: ["oracle db", "oracle database"],
  MongoDB: ["mongo"],
  Redis: [],
  Cassandra: [],
  DynamoDB: [],
  Elasticsearch: ["elastic search", "opensearch"],
  SQLite: [],
  Supabase: [],
  Firebase: ["firestore"],
  Snowflake: [],
  BigQuery: ["big query"],
  Redshift: [],
  Databricks: [],

  // Cloud / DevOps
  AWS: ["amazon web services", "ec2", "s3", "lambda", "aws lambda", "cloudformation"],
  Azure: ["microsoft azure"],
  "Google Cloud": ["gcp", "google cloud platform"],
  Docker: ["containers", "containerization"],
  Kubernetes: ["k8s", "eks", "aks", "gke"],
  Terraform: ["infrastructure as code", "iac"],
  Ansible: [],
  "CI/CD": ["ci / cd", "continuous integration", "continuous delivery", "continuous deployment"],
  Jenkins: [],
  "GitHub Actions": [],
  GitLab: ["gitlab ci"],
  Git: ["github", "version control"],
  Linux: ["unix", "ubuntu", "red hat", "rhel"],
  Nginx: [],
  Kafka: ["apache kafka"],
  RabbitMQ: [],
  Prometheus: [],
  Grafana: [],
  Datadog: [],
  Splunk: [],
  "Site reliability": ["sre", "site reliability engineering"],
  Observability: ["monitoring"],
  "Computer networking": ["tcp/ip", "dns", "vpn", "network engineering"],
  Cybersecurity: ["information security", "infosec", "security engineering"],
  "Penetration testing": ["pen testing", "pentesting"],
  SIEM: [],
  "Identity & access management": ["iam", "okta", "sso", "oauth", "saml"],
  "Cloud security": [],
  Compliance: ["soc 2", "soc2", "iso 27001", "hipaa", "gdpr", "pci", "pci dss", "sox"],

  // Testing / quality
  "Unit testing": ["unit tests", "tdd", "test-driven development"],
  Jest: [],
  Cypress: [],
  Playwright: [],
  Selenium: [],
  "QA testing": ["quality assurance", "qa", "manual testing", "test automation", "automated testing"],

  // Data / ML / AI
  "Machine learning": ["ml", "machine-learning"],
  "Deep learning": [],
  "Artificial intelligence": ["ai"],
  "Generative AI": ["genai", "llm", "llms", "large language models", "prompt engineering", "rag"],
  NLP: ["natural language processing"],
  "Computer vision": [],
  TensorFlow: [],
  PyTorch: [],
  "scikit-learn": ["sklearn", "scikit learn"],
  Pandas: [],
  NumPy: [],
  "Apache Spark": ["pyspark", "spark sql"],
  Hadoop: [],
  Airflow: ["apache airflow"],
  dbt: [],
  ETL: ["elt", "data pipelines", "data pipeline"],
  "Data analysis": ["data analytics", "analytics"],
  "Data engineering": [],
  "Data modeling": ["data modelling"],
  "Data visualization": ["data visualisation", "dashboards", "dashboarding"],
  Statistics: ["statistical analysis", "statistical modeling"],
  "A/B testing": ["ab testing", "experimentation", "split testing"],
  Tableau: [],
  "Power BI": ["powerbi"],
  Looker: [],
  "Microsoft Excel": ["ms excel", "advanced excel", "excel spreadsheets", "vlookup", "pivot tables", "spreadsheets"],
  "Google Sheets": [],
  MLOps: [],

  // Design / product
  Figma: [],
  "Sketch app": ["sketch app", "sketchapp"],
  "Adobe Creative Suite": ["adobe creative cloud", "adobe cc"],
  Photoshop: ["adobe photoshop"],
  Illustrator: ["adobe illustrator"],
  InDesign: ["adobe indesign"],
  "After Effects": [],
  "UI design": ["user interface design", "visual design"],
  "UX design": ["user experience", "ux"],
  "UX research": ["user research", "usability testing"],
  Prototyping: ["wireframing", "wireframes"],
  "Product management": ["product manager", "product strategy", "product roadmap", "roadmapping"],
  "Product analytics": ["mixpanel", "amplitude"],
  Agile: ["agile methodology"],
  Scrum: ["scrum master"],
  Kanban: [],
  Jira: ["atlassian jira"],
  Confluence: [],
  "Project management": ["project manager", "pmp", "program management"],
  "Stakeholder management": [],
  "Requirements gathering": ["business requirements", "user stories"],

  // Marketing / sales / customer
  SEO: ["search engine optimization"],
  SEM: ["search engine marketing", "google ads", "ppc", "paid search"],
  "Content marketing": ["content strategy", "copywriting"],
  "Social media marketing": ["social media"],
  "Email marketing": [],
  "Marketing automation": ["marketo", "pardot"],
  HubSpot: [],
  "Google Analytics": ["ga4"],
  "Growth marketing": ["growth hacking", "demand generation", "demand gen", "lead generation"],
  "Brand marketing": ["branding", "brand strategy"],
  "Product marketing": ["go-to-market", "gtm"],
  Salesforce: ["sfdc", "salesforce crm"],
  CRM: [],
  "B2B sales": ["saas sales", "enterprise sales"],
  "Account management": ["account manager"],
  "Business development": ["bizdev"],
  "Customer success": ["customer success manager"],
  "Customer support": ["customer service", "zendesk", "help desk", "helpdesk"],
  Negotiation: [],
  "Cold calling": ["prospecting"],

  // Finance / accounting / business
  Accounting: ["gaap", "accounts payable", "accounts receivable", "general ledger"],
  "Financial analysis": ["financial modeling", "financial modelling", "fp&a", "forecasting", "budgeting"],
  QuickBooks: [],
  NetSuite: [],
  SAP: [],
  "Workday HCM": ["workday financials"],
  Auditing: ["audit", "internal audit"],
  "Tax preparation": ["taxation", "tax accounting", "tax returns"],
  "Risk management": [],
  Payroll: [],
  Bookkeeping: [],
  "Supply chain": ["logistics", "procurement", "inventory management"],
  "Operations management": ["business operations"],
  "Six Sigma": ["lean six sigma"],
  Recruiting: ["talent acquisition", "sourcing", "recruitment"],
  "Human resources": ["hr", "hris", "people operations"],

  // Healthcare / other licensed fields
  "Patient care": [],
  EMR: ["ehr", "epic emr", "epic systems", "cerner", "electronic medical records", "electronic health records"],
  "Medical billing": ["medical coding", "icd-10", "cpt coding"],
  CPR: ["bls", "acls"],
  "Registered Nurse": ["rn"],
  "Clinical research": ["clinical trials"],
  Pharmacy: [],
  Litigation: ["paralegal", "contract management", "legal research"],
  "Technical writing": ["technical writer"],
  Teaching: ["curriculum development", "lesson planning"],

  // Generic soft skills: recognised, never scored (spec 006)
  Communication: ["communication skills", "written communication", "verbal communication"],
  Leadership: ["team leadership", "people management"],
  Teamwork: ["collaboration", "cross-functional"],
  "Problem solving": ["problem-solving", "critical thinking"],
  "Time management": ["organizational skills", "multitasking"],
  Mentoring: ["coaching"],
}

/** Recognised in text but too common to say anything about fit. */
export const GENERIC_SKILLS = new Set([
  "Communication",
  "Leadership",
  "Teamwork",
  "Problem solving",
  "Time management",
  "Mentoring",
])
